In [5]:
import pandas as pd
import numpy as np

# Nearest Neighbour

In [103]:
x = np.random.rand(1000 , 3)


In [104]:
x.shape

(1000, 3)

In [107]:
y = x.reshape(1000 , 1 , 3)

In [120]:
diff = y -x

In [122]:
diff.shape

(1000, 1000, 3)

In [133]:
D = (diff**2).sum(axis=2)

In [141]:
D.shape

(1000, 1000)

In [137]:
i = np.arange(1000)

In [139]:
D[i,i] = np.inf

In [144]:
res = np.argmin(D , 1)

In [163]:
res[:10] # Nearest Neighbors indices

array([366, 703, 243, 622, 700, 840, 296, 648, 222, 551])

In [152]:
from sklearn.neighbors import NearestNeighbors

In [158]:
d , i = NearestNeighbors().fit(x).kneighbors(x  ,2)

In [162]:
i[:10 , 1]

array([366, 703, 243, 622, 700, 840, 296, 648, 222, 551])

# Clustering

In [171]:
tri = np.array([[1., 1.],[3., 1.],[2., 3.]])

In [172]:
centroid = tri.mean(axis =0)

In [173]:
centroid

array([ 2.        ,  1.66666667])

In [174]:
centroid.dtype

dtype('float64')

In [178]:
(tri**2).sum(axis = 1)**0.5  # distance from origin

array([ 1.41421356,  3.16227766,  3.60555128])

In [198]:
X = np.repeat([[5, 5], [10, 10]], 5, axis=0)

In [222]:
X = X+ np.random.rand(10,2)

In [217]:
centroid_point = np.array([[4,4],[9,9]])

In [218]:
centroid_point = np.expand_dims(centroid_point , 1)

In [236]:
euclidian_distance = ((X - centroid_point)**2).sum(axis = 2)

In [237]:
euclidian_distance.shape

(2, 10)

In [241]:
min_indices = np.argmin(euclidian_distance , axis=0)

In [242]:
cluster_centroids = centroid_point[min_indices] 

In [243]:
cluster_centroids

array([[[4, 4]],

       [[4, 4]],

       [[4, 4]],

       [[4, 4]],

       [[4, 4]],

       [[9, 9]],

       [[9, 9]],

       [[9, 9]],

       [[9, 9]],

       [[9, 9]]])