In [1]:
import numpy as np

In [35]:
x = np.array([[1],[7],[8]])

In [45]:
z = np.array([1,7,8])

In [43]:
z = np.array([[1,7],[2,9],[5,5]])

In [46]:
z.shape

(3,)

In [50]:
j= np.expand_dims(z,axis=1)

In [51]:
j.shape

(3, 1)

In [52]:
j

array([[1],
       [7],
       [8]])

In [53]:
x.shape

(3, 1)

In [64]:
y = np.expand_dims(x, axis=1)

In [65]:
y.shape

(3, 1, 1)

In [66]:
y

array([[[1]],

       [[7]],

       [[8]]])

In [67]:
y = np.array([[1,2,3,4],[3,4,5,6]])

In [68]:
y.shape

(2, 4)

In [75]:
j= np.expand_dims(y,axis=2)

In [76]:
j.shape

(2, 4, 1)

In [77]:
j


array([[[1],
        [2],
        [3],
        [4]],

       [[3],
        [4],
        [5],
        [6]]])